### ISSUE TITLE
BundlePhobia (and other bundlers?) entrypoint errors

### ISSUE THREAD

**Issue by riongull** [dashhive/DashTx.js#51]
Inspecting https://bundlephobia.com/package/dashtx@0.14.1 (and 0.14.0) results in an EntryPointError, this resolves the EntryPointError issue as well as some issues with using the package as an ESM module.

See https://bundlephobia.com/package/dashtx@0.14.2-1 for this code working at bundlephobia.

_Originally posted by @jojobyte in https://github.com/dashhive/DashTx.js/pull/43_

**Comment by riongull** [comment]
The latest version of DashTx still can't find the entry point. 

https://bundlephobia.com/package/dashtx@0.14.4

> EntryPointError
We could not guess a valid entry point for this package. Perhaps the author hasn't specified one in its package.json ?

**Comment by jojobyte** [comment]
Fixed in #43
