### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getPrivateKey')

### ISSUE THREAD

**Issue by jojobyte** [dashhive/DashTx.js#72]
![image](https://github.com/user-attachments/assets/691ffd2f-7814-430b-8aad-5e6444baf725)

https://github.com/dashhive/DashTx.js/blob/main/dashtx.js#L253-L255 this line breaks https://github.com/dashhive/DashWallet.js/blob/main/dashwallet.js#L17 for `"dashtx": ">=0.17",` and `"dashtx": "^0.18.1",`

```js
Tx.create = function (keyUtils) {
    if (!keyUtils.getPrivateKey) {
      throw new Error(`you must create with 'opts.getPrivateKey()'`);
    }
// ...
}
```

`dashtx` version `0.16` and below seems to be fine.

**Comment by coolaj86** [comment]
It's not a bug, it's a breaking change for pre-v1.0.

Stick with 0.17.x for the previous behavior.

The new documented behavior always requires the keyUtils to be passed in.

However, I'm open to making that a `if (!keyUtils?.getPrivateKey)`.
